---
- name: Add EPEL repository
  package:
    name: epel-release
    state: latest
  tags:
    - skip_ansible_lint

- name: Uninstall Yum Ansible packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "ansible"
    - "python-jinja2"

- name: Install Pip package from Yum
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ ansible_yum_pip_packages }}"

- name: Install Ansible package from Pip
  pip:
    name: "{{ ansible_pip_ansible_package_name }}"
    version: "{{ ansible_pip_ansible_package_version }}"
